# Pull base image.
FROM ubuntu:trusty

MAINTAINER LeeYen <lee.yen@eztable.com>

# This is read only key for building
COPY config/githubkey /root/.ssh/id_rsa

# PHP related
#RUN apt-get update && apt-get --assume-yes install build-essential curl wget libcurl4-openssl-dev libxml2-dev php-apc \
# php-gettext php-pear php5-imagick php5-curl php5-dev libgpgme11-dev libpcre3-dev \
# php5-fpm php5-gd php5-imap php5-redis \
# php5-mcrypt php5-mysqlnd php5-sybase php5-xdebug \
# php5-intl nginx git && \
# curl -sL https://getcomposer.org/installer | php && \
# mv composer.phar /usr/local/bin/composer && \
# echo "cgi.fix_pathinfo = 0;" >> /etc/php5/fpm/php.ini && \
# pecl install -f solr-2.4.0 && \
# pecl install -f mysqlnd_ms && \
# pecl install -f gnupg && \
# pear clear-cache && \
# pear update-channels && \
# pear upgrade && \
# pecl install mongodb && \
# echo "extension=gnupg.so" >> /etc/php5/mods-available/gnupg.ini && \
# ln -s /etc/php5/mods-available/gnupg.ini /etc/php5/cli/conf.d/20-gnupg.ini && \
# ln -s /etc/php5/mods-available/gnupg.ini /etc/php5/fpm/conf.d/20-gnupg.ini && \
# echo "extension=solr.so" > /etc/php5/mods-available/solr.ini && \
# ln -s /etc/php5/mods-available/solr.ini /etc/php5/cli/conf.d/20-solr.ini && \
# ln -s /etc/php5/mods-available/solr.ini /etc/php5/fpm/conf.d/20-solr.ini && \
# echo "extension=mysqlnd_ms.so" > /etc/php5/mods-available/mysqlnd_ms.ini && \
# ln -s /etc/php5/mods-available/mysqlnd_ms.ini /etc/php5/cli/conf.d/20-mysqlnd_ms.ini && \
# ln -s /etc/php5/mods-available/mysqlnd_ms.ini /etc/php5/fpm/conf.d/20-mysqlnd_ms.ini && \
# echo "extension=mongodb.so" > /etc/php5/mods-available/mongodb.ini && \
# ln -s /etc/php5/mods-available/mongodb.ini /etc/php5/cli/conf.d/20-mongodb.ini && \
# ln -s /etc/php5/mods-available/mongodb.ini /etc/php5/fpm/conf.d/20-mongodb.ini && \
# echo "StrictHostKeyChecking no"  > /root/.ssh/config && \
# chmod 400 /root/.ssh/id_rsa
#
## html to pdf
#RUN apt-get update && apt-get install -y xorg libssl-dev libxrender-dev gdebi
#RUN cd /tmp && \
#    wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb && \
#    gdebi --n wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
#RUN apt-get -y install xvfb
#RUN apt-get install fonts-wqy-microhei
#
#RUN apt-get remove -y vim-common
#RUN apt-get install -y vim
#
#RUN echo 'LANG="en_US.UTF-8"' > /etc/default/locale && \
#    echo 'LANG="zh_TW.UTF-8"' > /etc/default/locale && \
#    echo 'LANG="zh_HK.UTF-8"' > /etc/default/locale && \
#    echo 'LANG="zh_CN.UTF-8"' > /etc/default/locale && \
#    echo 'LANG="th_TH.UTF-8"' > /etc/default/locale && \
#    echo 'LANG="id_ID.UTF-8"' > /etc/default/locale && \
#    echo 'LANG="ko_KR.UTF-8"' > /etc/default/locale && \
#    echo 'LANG="ja_JP.UTF-8"' > /etc/default/locale && \
#    locale-gen en_US.UTF-8 && \
#    locale-gen zh_TW.UTF-8 && \
#    locale-gen zh_CN.UTF-8 && \
#    locale-gen zh_HK.UTF-8 && \
#    locale-gen th_TH.UTF-8 && \
#    locale-gen id_ID.UTF-8 && \
#    locale-gen ko_KR.UTF-8 && \
#    locale-gen ja_JP.UTF-8
#
#RUN apt-get purge -y php5-apcu
#RUN cd /tmp && \
#    wget http://www.kiloroot.com/wp-content/uploads/2015/08/php5-apcu_4.0.6-1_amd64.deb && \
#    dpkg -i php5-apcu_4.0.6-1_amd64.deb
#RUN cd /tmp && \
#    rm php5-apcu_4.0.6-1_amd64.deb
#
#COPY ./config/php5/fpm/php.ini /etc/php5/fpm/php.ini
#COPY ./config/php5/fpm/www.conf /etc/php5/fpm/pool.d/www.conf
#COPY ./config/php5/cli/php.ini /etc/php5/cli/php.ini
#COPY ./config/php5/mysqlnd_ms_plugin.ini /etc/eztable/php5/mysqlnd_ms_plugin.ini
#COPY ./bin/run.sh /eztable/bin/run.sh
#
#RUN sed -i -e "s/sendfile on;/sendfile off;/g" /etc/nginx/nginx.conf
#
#COPY ./config/eztable/kernel.inc.php /etc/eztable/kernel/config.inc.php
#
#ONBUILD COPY ./config/nginx/default /etc/nginx/sites-available/default
#
ENTRYPOINT ["bash", "/eztable/bin/run.sh"]
